
services:
  postgres:
    image: 'postgres:13'
    container_name: 'java-postgres'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: java
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:  # Добавьте эту секцию
  postgres_data:  # Определение тома